language: go
sudo: required
go:
- 1.10.x
services:
- docker
stages:
- test
- name: push
  if: $QUAY_USERNAME != "" $QUAY_PASSWORD != ""
jobs:
  include:
  - stage: compile
    script:
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make setup test
    - printenv
  - stage: deploy
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io;
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make build-and-push
      TAG=$TRAVIS_COMMIT;
env:
  global:
    secure: o7pveN4X56bRzvQi+W30YiAAqUTppqH8exttN45Fg4AQv/Sqcz2W8zBNet/0HwDV9bwblaByaQk7BBJ9wn2/3vV2h+RWzCeaWN4xESydtYRupXbWBU00zdMirDfCqEZKOf8SXkQJu5WuNbDgY7o1XWQH7ivJP7rJDgDONl/YAqkxYazPafqHR2R+szK98GRHnWo1+mRh0ExD9R6A/oG49z3RnoZGfUWzue5R/sOJh2aumvtNI2VnV0h67z0UY7+nvlToptJmAOGu5TrEHsgENfm0qQew6NhC3aNTiTg32wx6d3ClC2tFKlYrjTXhp4lw/Rt7MqLnVtJafMkknrduk7vGFRa0ly4xZmIdIL8qKo0PbKJzXzywrKV7DqK53O2BaAjdwHozFM+gqeLcgkzUx/SRdfza6or0uzWN1dAWdetQUUf9DI5sZulixQH1MmIlL/swvCUnEz7OjDusDNdJxMbBnZf6kL05fhFbR58DnFyPct2fG6qwBlzD1e4LMdD6zfKInkXven4rTqIhjb3bUA3wTajlei51I/xNjCr4dBn9pg3VhAUwyVlUUbllosOQBs1i8qJWumG46VZOF7y4ju2FfunHHyNjbyLVt/19Oo1KEio8FoGNpzkM5sZipITuI6tmPaPy3uQtWlptZGMvA1/EqsjFkqTto6ElhsJLKRs=
