language: go
sudo: required
go:
- 1.10.x
services:
- docker
stages:
- test
- name: push
  if: $QUAY_USERNAME != "" $QUAY_PASSWORD != ""
jobs:
  include:
  - stage: compile
    script:
    - echo $QUAY_USERNAME
    - printenv
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make setup test
  - stage: deploy
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io;
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make build-and-push
      TAG=$TRAVIS_COMMIT;
env:
  global:
    secure: KxJIJo/oTxZjDPpPvMCF32OeOTI7+YaEX9A6PnXGUQ27X09VvWLEHkBpjvILuuDlYadj7rKxuv1GyUeJXJe3FqNTK3cgaCit1jIytAxp2DJCtF3wr0gLqohdDJ/7dueaNBV0+R6IGkY1bfjw0PfQEoHYR7hzCfv8YeeG+gaRtQsJfN3ZdaqG0WUqRdl6Y8fws+RMED3lugS0vsV7jYllBkQQAJQJ4LHT8SwpjrkwuuoKBUa3+RhQtZj7EIf7Cn+aDGzMEpdyDrMQPSfEVMOSK1hzugrV4u10iWFmBSj4X/v21qdOAGizVNM5ERYIpeOD/RXMgSOIJQ1rp8zDB0THltrbhpx7vC2Qs3GB+HV2z9nk5KfmCkn2gnZNnCFITtaMbBpC5D9pTV2eCS/8lEM5XWh0RkgEJsToY+pRkO6kxRs+jQipDFhavYII7J9p4wHBKkaoY6fOk18rdJvEoocXpv2cG4qXUt74oTBF+56eQ8HJLnkC5HyhCCORbuoUyC5w6TCOQjUBJ4ZuH0Ie5XhxBlAmDshsnVCYO2ILiC/RItA0Qfjn84yi+7myljSlrCVpSMcnKDwGAeJ+9ftG5UeqU8smSFMRC0+opb2PdbExejCTUyW0LQ9F7bG6XClBgRZJPkwnal8mtxmVWKrIGZxTOvk4QuMUszF58/V8USgoybk=
