language: go
sudo: required
go:
- 1.10.x
services:
- docker
stages:
- test
- name: push
  if: $QUAY_USERNAME == "" $QUAY_PASSWORD != "" $NOT_HERE != ""
jobs:
  include:
  - stage: compile
    script:
    - printenv
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make setup test
  - stage: push
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io;
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make build-and-push
      TAG=$TRAVIS_COMMIT;
