language: go
sudo: required
go:
- 1.10.x
services:
- docker
stages:
- test
- name: push
  if: $QUAY_USERNAME != "" $QUAY_PASSWORD != ""
jobs:
  include:
  - stage: compile
    script:
    - echo $QUAY_USERNAME
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make setup test
  - stage: deploy
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io;
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make build-and-push
      TAG=$TRAVIS_COMMIT;
env:
  global:
  - secure: e+r+DjKu7+1dk5se9hfk5LbYyp7J2O3cUNLOnZYUGKlkZ4U3Qcy3L4dqepCcfisgboh8qzfGOz+AcmTaMeZsNIp45DMoVQnpQbN50l+KcvJ5glMkWBC8CNIBk/+4jyVvVf3KsDlWs3SGhoJ6msTfueNbe5uooUMWRRZhjQopwW+lV14IL9pz3/wLRz1XN24tmThUVL/gOmWHLgcEiHm7vMEjmdi9Pfn74qwWXcki4DY5R04J2aEz46o6e+y2y3m1K+8p2uwwpQhrPJQAHsyJ6TTXiRBDwi9ZGYL2DQh9pxRfr8eIWJEsATKAZcp0U0NKmkXUOtV5xpUK2e6NFam+EC9+iH+DaZD1ygUhKDP6CQZlFEdJOYjIjx8UEAy3Wyd+o70Fr2R80fOlykQIR3WJpDxkUV0lj5cXlItYnGKnw/J3baEjvIYn6uBdFb71hz0x5S6350f+WHmkB21Btg7UPufCLtAwAcE7gMVakyWweNSq41OeaHntgEFaevxU7FodXgCd3307A/wPuYDwRUFt6EPPTlpiiOtWFck4cpmvgGCbHY9yjOTTHzVgK5vCR3GmwDUxj6HC+f2CI1EL7xzJ9/1b8dMEJh8U5ZBtXpRBAUqbutW/+uQ5ODtfXYRdnHjVIoOw8jeKqjWOE03+QTK6/M89O0F2uIrbEaXh/ZPzWsc=
