language: go
sudo: required
go:
- 1.10.x
services:
- docker
stages:
- test
- name: push
  if: $QUAY_USERNAME != "" $QUAY_PASSWORD != ""
jobs:
  include:
  - stage: compile
    script:
    - echo $QUAY_USERNAME
    - printenv
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make setup test
  - stage: deploy
    script:
    - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io;
    - cd $HOME/gopath/src/github.com/integr8ly/keycloak-operator && make build-and-push
      TAG=$TRAVIS_COMMIT;
env:
  global:
    secure: F2teyGsXhL+InPvXqYZIxCETXyiaxBoioSWDDllQy90mhP+vaA4m1YixHJu9AqXrlhq6TKw8rozdwpP6o39ooyuZIjeJDlA+wY8TeR1XiSJJH2QJsWV/TBu538Ed0e4hlGhm9A80gtaNAffidEdNDQfU+8SlO/eqEilKhFvTHE9VD2Wh0yDGVF8z3UduAj5yze7ailpPKL1eB9hxTPHTzCdmcCJPMffCW1WA7cdK+zQicdQiXQm+G5i2PYKRDZ8qrSsZs3Qhm0n6SbvkedDsE2M6CRgYlitnLdqOxMfEG1mHp3fq0ePwHholWmbNCxNx4Z1ZHQQYF2AzdAwofkKHTmHOP/3N+/JOirH2Zi//0MTISZcDzebTdachBEcdZ/866AEA2lo9LiynH0zSQLRdVisUZuYD/Py0vlYnuJ3N/sHf9WZr99uTtMWyZk4+o+rD0nBSWls9SJfQquy6ikGApSI0u9UVFaCxSCeQMqsHQfEZ69oCVHzT+mQZtdRZUGzC/zZvpAJjPaURVCxDmfksGxBpmCJVnHU2yIw10cGHO5MzG29FnHOovy9qZ13ZlKwNGqx75nebDyfcF0BEkpH1g89sz+TRV67N+F+IqvXTku+lQOcZfC4igqNRsEWP5M1Tua6DjPiPcEiBhdigPJRfO3JM8immvy3naZtVNB0owI4=
