apiVersion: aerogear.org/v1alpha1
kind: Keycloak
metadata:
  finalizers:
  - finalizer.org.aerogear.keycloak
  name: integreatly
spec:
  realms:
  - clients:
    - attributes: {}
      bearerOnly: false
      clientAuthenticatorType: client-secret
      #this is the secret that is needed by openshift config
      secret: somethingGenerated
      clientId: openshift
      consentRequired: false
      directAccessGrantsEnabled: true
      enabled: true
      frontchannelLogout: false
      fullScopeAllowed: true
      implicitFlowEnabled: false
      protocol: openid-connect
      publicClient: false
      redirectUris:
      - https://cloudservices.skunkhenry.com:8443/*
      standardFlowEnabled: true
      #this is the secret that the client and client secret will be stored in
      outputSecret: openshift-client
      webOrigins: []
    enabled: true
    id: openshift
    realm: openshift
    users:
    - clientRoles:
        account:
        - manage-account
        - view-profile
      email: admin@example.com
      emailVerified: false
      enabled: true
      firstName: ""
      lastName: ""
      realmRoles:
      - offline_access
      - uma_authorization
      username: admin@example.com
      outputSecret: openshift-admin
    - clientRoles:
        account:
        - manage-account
        - view-profile
      email: evals@example.com
      emailVerified: false
      enabled: true
      firstName: ""
      lastName: ""
      realmRoles:
      - offline_access
      - uma_authorization
      username: evals@example.com
      outputSecret: openshift-evals
  version: 7.2.2.GA
