apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedserviceactions.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedServiceAction
    listKind: SharedServiceActionList
    plural: sharedserviceactions
    singular: sharedserviceaction
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            providedParams:
              type: object
            serviceType:
              type: string