apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sharedserviceplans.aerogear.org
spec:
  group: aerogear.org
  names:
    kind: SharedServicePlan
    listKind: SharedServicePlans
    plural: sharedserviceplans
    singular: sharedserviceplan
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceType:
              type: string
            instanceParams:
              type: object
            bindParams:
              type: object