apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  name: keycloak.v0.0.1
  namespace: rhsso
spec:
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: keycloak-operator
        rules:
        - apiGroups:
          - aerogear.org
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - deploymentconfigs
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - template.openshift.io
          resources:
          - processedtemplates
          verbs:
          - "*"
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - "*"
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - "*"
      deployments:
      - name: keycloak-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: keycloak-operator
          template:
            metadata:
              labels:
                app: keycloak-operator
            spec:
              containers:
                - name: keycloak-operator-olm-owned
                  image: quay.io/integreatly/keycloak-operator:0.0.2
                  command:
                  - keycloak-operator
                  imagePullPolicy: Always
                  env:
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: OPERATOR_NAME
                    value: "keycloak-operator"
                  - name: MY_POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: MY_POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: keycloak-operator
              serviceAccount: keycloak-operator
  customresourcedefinitions:
    owned:
      - description: Represents an instance of a Keycloak application
        displayName: Keycloak Application
        kind: Keycloak
        name: keycloaks.aerogear.org
        version: 0.0.1
  version: 0.0.1
  displayName: Keycloak
  labels:
    olm-owner-enterprise-app: keycloak-operator
    olm-status-descriptors: keycloak.v0.0.1
